### ISSUE TITLE
cfspreadsheet action="read" gives error

### ISSUE THREAD

**Issue by vikaskanani** [Leftbower/cfspreadsheet-lucee#1]
I get java.lang.NumberFormatException when reading xlsx file.

Lucee version: 4.5.1.008

![error on reading xlxs file](https://cloud.githubusercontent.com/assets/439199/6651878/65685940-ca7e-11e4-8559-8d3032032d7c.png)

**Comment by Leftbower** [comment]
It is hard to tell anything from that error.

Does this happen for any xlsx file or just one in particular? I can open any xls, xlsx file on Lucee 4.5.1.008 on both Tomcat 7 and 8, Windows 32b and 64b. Have you tried downloading the cfspreadsheet-examples.zip file and seeing if you can run all of those tests?

**Comment by vikaskanani** [comment]
Thanks for quick and prompt response. I was in rush, I'll come up with more
details.

Vikas Patel
about.me/vikaskanani
[image: Vikas Patel on about.me]
  http://about.me/vikaskanani

**Comment by vikaskanani** [comment]
I had a file that was modified by Kingsoft spreadsheet which is not readable with cfspreadsheet tag, but the same issue happens with Railo as well. So I am closing this issue, considering your fork is for installation on Lucee.

**Comment by cfsimplicity** [comment]
Might be worth trying the file with https://github.com/cfsimplicity/lucee-spreadsheet which implements the read method differently and uses a newer version of POI.

**Comment by vikaskanani** [comment]
@cfsimplicity great! I was just searching what was the issue.. Error was throwing from poi-export-utility.jar file and I wasn't able to find the source code. But component method works great! I may need to convert the tag to script code, but that is okay if I am getting POI 3.11 library... Thanks man!
