### ISSUE TITLE
Numbers being pre-pended with apostrophes

### ISSUE THREAD

**Issue by phantom42** [Leftbower/cfspreadsheet-lucee#3]
Using version 4.1.0 with Lucee 4.5.4.017, I am trying to insert a number into a cell. The value is inserted, but is always pre-pended with a single apostrophe.

`<cfset SpreadSheetSetCellValue(sheet, 33.5, 5, 1) />`

results in 

> `33.5

Additionally, probably caused by this issue, dataFormat attributes are not properly applied.

`<cfset spreadsheetformatcell(sheet, {dataformat='0.00'}, 5,1)>`

The dataformat is not applied. Other formatters, such as color or bold, work fine.

Of note, if I add the values as an entire row (i.e spreadsheetAddRow), the numbers go in as expected.

**Comment by Leftbower** [comment]
Hello Joe. I see the issue and the `setCellValue()` is `javaCast`ing the value to a string before setting it. This is on line 1951 of org.cfpoi.spreadsheet.Spreadsheet.cfc

In fact I notice we have a comment mentioning whether this is necessary and/or would cause any problems right before we do that. It likely hasn't been looked at in a long time. I'll try to give it a go, but it might be some time before I can get to it what with year-end at work and the holidays.

You could certainly remove the javaCast on your setup and play around as well. That very well may be an easy fix, I just need to test it before committing it...

**Comment by phantom42** [comment]
Removing the javaCast does seem to work in this instance. I'm not 100% sure it's not going to cause other issues down the line with other data types, but this is a very limited use bit of functionality in our app for the time being.

**Comment by DaveAndersonxx** [comment]
I know this is an old old issue, but can somebody detail for me the steps I need to take to update the tag to remove the javaCast()

I'm having this problem with numbers written as strings, and I haven't worked with lex or lar files before.  It's not clear to me how to update that.

Thanks

**Comment by Leftbower** [comment]
Dave - this version of Lucee is not even being supported any longer. However, the source for the `.lex` is in this repository and the `.lex` is just a `zip` file with all CFML code inside. You can just open it and modify the file as discussed above and you should be good to go.

**Comment by DaveAndersonxx** [comment]
> Dave - this version of Lucee is not even being supported any longer. However, the source for the `.lex` is in this repository and the `.lex` is just a `zip` file with all CFML code inside. You can just open it and modify the file as discussed above and you should be good to go.

perfect, thanks.  I knew it was the wrong version; I just ended up here because this is where the fix is discussed. I think that's all I needed to know, so thanks again for the reply.
